version: '3.1'

networks:
  laravel:

services:
  
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:8080"  
      # En el archivo nginx/default esta declarado conjuntamente por este puerto en especifico
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d
    depends_on:
      - php
      - mysql
      - phpmyadmin
    networks:
      - laravel

  mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel_master
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php_my_admin
    ports:
      - "8181:80"
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: homestead
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel


  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
